name: trina_grid
description: A data grid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 2.1.0
repository: https://github.com/doonfrs/trina_grid
issue_tracker: https://github.com/doonfrs/trina_grid/issues

topics:
 - flutter
 - tables
 - data-grid
 - data-table

screenshots:
  - description: 'TrinaGrid Logo'
    path: screenshots/trina_grid.png

documentation: https://github.com/doonfrs/trina_grid/blob/main/doc/index.md

environment:
  sdk: ^3.6.1

# This allows the package to be run as an executable
executables:
  trina_grid: trina_grid

dependencies:
  flutter:
    sdk: flutter
  # Follows the intl version included in Flutter.
  # https://github.com/flutter/flutter/blob/84a1e904f44f9b0e9c4510138010edcc653163f8/packages/flutter_localizations/pubspec.yaml#L11
  intl: ^0.20.2
  rxdart: ^0.28.0
  collection: ^1.19.1
  path: ^1.9.1
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
